name: 'DigitalOcean Janitor'
author: 'Rancher Sandbox'
description: 'Clean-up Digital Ocean resources based on a TTL.'
inputs: 
  regions:
    description: 'A comma separated list of regions to clean resources in. Use the slug (i.e. nyc1,lon1). You can use * for all regions.'
    required: true
  allow-all-regions:
    description: 'Set to true if you want to allow cleaning resources in all regions. If true then * must be used for regions.'
    required: false
    default: 'false'
  ttl:
    description: 'The duration that a resource can live for. For example, use 24h for 1 day.'
    required: true
  commit:
    description: 'Should the action just report or do the actual delete.'
    required: false
    default: 'false'
  token:
    description: 'The Digital Ocean API token to use. It must have Write scope.'
    required: true
  ignore-tag:
    description: 'The name of the tag that indicates a resource should not be deleted.'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/rancher-sandbox/digitalocean-janitor:v0.1.0'
branding:
  icon: 'delete'
  color: 'blue'